### ISSUE TITLE
Fails on personal numbers that end with 0

### ISSUE THREAD

**Issue by denizdogan** [personnummer/python#1]
`personnummer.personnummer.valid` returns `False` if the personal number ends with 0.

```
>>> valid('851226-2190')
False
>>> valid('8512262190')
False
>>> valid('198512262190')
False
```

`False` is returned because of `int(check) > 0` [on line 68](https://github.com/personnummer/python/blob/66c6615b648fab005dd88eda60647a343cd04b5a/personnummer/personnummer.py#L68). I'm not sure why that check is being done? As far as I can tell, the "control digit" is allowed to be 0, I actually know a person whose control digit is 0 (it's not the personal number in the example though, it was randomly generated).

So I think if you just remove `int(check) > 0`, the bug would be resolved.

**Comment by frozzare** [comment]
Thanks, I’m on vacation right now so a pull request would be great!
tis 10 juli 2018 kl. 12:14 skrev Deniz Dogan <notifications@github.com>:
