### ISSUE TITLE
Question: Why were most of the test cases removed in the last commit?

### ISSUE THREAD

**Issue by dannyhajj** [personnummer/python#14]
In the last commit<sup>[[1]][111bbd]</sup>, a lot of the tests were removed. What's the reasoning behind that?
I think it would be more valuable to have the same tests between the different libraries (like the [PHP library](https://github.com/personnummer/php/blob/master/tests/PersonnummerTest.php)). In order to make sure they all behave the same way for every input.

[111bbd]: https://github.com/personnummer/python/commit/111bbde78344cfc1b4fe8517251bc713d9fbdc54

**Comment by frozzare** [comment]
All packages should be updated with new test cases to ensure that we don't use numbers that we shouldn't. PHP library will also be updated.
