### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by frozzare** [personnummer/python#16]
This package is not maintained as much because none of the core people use Python on a hobby level or at work, but we want it to be maintained.

We have a [spec (v3)](https://github.com/personnummer/meta#package-specification-v3) that should be followed for all packages.

Comment or send me a email (https://frozzare.com/) if you're interested! You will be invited to our slack.

**Comment by Buscedv** [comment]
I'm interested

**Comment by frozzare** [comment]
Great @Buscedv! Sent you an invite to Slack to your GitHub email.
