### ISSUE TITLE
[Q] - Current structure of the class initialisation has several problems and doesn't follow Python best practices

### ISSUE THREAD

**Issue by dannyhajj** [personnummer/python#23]
```python
    def __init__(self, ssn, options=None):
        """
        Initializes the Object and checks if the given Swedish personal identity number is valid.
        :param ssn
        :type ssn str
        :param options
        :type options dict
        """

        if options is None:
            options = {}

        self.options = options
        self.parts = self.get_parts(ssn)

        if self.valid() is False:
            raise PersonnummerException(
                str(ssn) + ' Not a valid Swedish personal identity number!')

```
ref: https://github.com/personnummer/python/blob/3780ed3c959b8ffc33c187679c659f0f8fd64181/personnummer/personnummer.py#L13

1. What's the purpose of using a dictionary for `options`? Using a `**kwargs` argument is better.
2. `self.parts = self.get_parts(ssn)` This part of the code breaks the instance. In python, there are no private class method, but a function is implied as private by prepending an underscore to its name (`_`). In this case, `get_parts` is public. And running the following is actually changing instance variables:

    ```
    pno = Personnummer(8507099805)
    pno.getParts("somethingelse")
    ```

I wouldn't mind fixing these and sending a PR, but changing both of these can be breaking changes, let me know if that's okay.

**Comment by frozzare** [comment]
Nice find! Feel free to fix it 👍 

Options argument isn't used for something, only exists for the feature if and when we need options. So changing the options argument won't break anything.

`get_parts` shouldn't be public so I don't mind breaking that.

@Buscedv any thought?

**Comment by Buscedv** [comment]
No, sounds good

**Comment by dannyhajj** [comment]
Cool alright, I'll send a PR soon.
