### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by nnew2** [personnummer/python#5]
Hello,

It seems that there are issues in the validation process, as for an example the below returns True

`from personnummer import personnummer

print personnummer.valid('MASKED')`

> pip show personnummer
Name: personnummer
Version: 1.0.2
Summary: Validate Swedish social security numbers
Home-page: http://github.com/personnummer/python
License: MIT
Location: /Library/Python/2.7/site-packages
Requires: 
Required-by:

**Comment by nnew2** [comment]
Due to sensitive information MASKED was sent to the repo owner in private.

**Comment by Johannestegner** [comment]
Hi there!

The code currently validate both "personnummer" and "samordningsnummer" which is a temporary type of personnummer used for none-permanent residents in Sweden.
We have been discussing if we should make this a flag (or rather, making turning it of a flag), but haven't decided yet.

The "samordningsnummer" works as this:

The first four digits (year(2), month(2)) is the same as with a standard personnummer, but the `day` have 60 added to it. So if it is between 61 and 91, it's a samordningsnummer.

Is your requirement that the code ONLY take personnummer or are samordningsnummer a legal value too?

**Comment by nnew2** [comment]
The value that passed the validity test starts with 07077676XX, i.e. Swedish mobile number.
Not sure if that would go under "samordningsnummer" ?

If parsed as an (int) then I presume the leading 0 would be removed leaving us with 7077676XX but still don't see how it would return as valid.

**Comment by Johannestegner** [comment]
070776-xxxx would parse as someone born 2017 07 16 and then depending on the last 4 digits, it may or may not be validated by the lunh algorithm. If you use a integer value, it will treat it as 07 yes.

**Comment by nnew2** [comment]
Thanks for the clarification.

But how can 070776 be parsed as 2017-07-16? Shouldn't that parse as 2007-07-76?

**Comment by Johannestegner** [comment]
Sorry, not 2017, 2007 of course, hehe.
The check we do to validate the "date of birth" is basically to check if it is a valid date and if it is not, we try it with -60 on the days to generate a valid day instead of the samordnings addition to the date. So 76 would be seen as 16 in the date test. That means that any value within the ranges of 1-31 and 61-91 (as long as it is a 31 day long month) is a valid number for the day part of the date.

**Comment by nnew2** [comment]
Ok, I see.

So this was pretty much a coincidence that the last four digits passed the lunh alg as well.
Regarding your discussion to add a flag to exclude samordningsnummer, I think that would be a good addition.

**Comment by frozzare** [comment]
Added flag to exclude samordningsnummer. Not released a new version yet. 
https://github.com/personnummer/python/commit/e99cfd501ccae921f0034d729242b424de0e086f
