### ISSUE TITLE
Follow the PEP8 coding style

### ISSUE THREAD

**Issue by dannyhajj** [personnummer/python#9]
Can the naming in the library follow the [PEP8 naming conventions][pep8-naming-conventions] before releasing the new changes?

```
def valid(s, includeCoordinationNumber = True):
```
should be 
```
def valid(s, include_coordination_number = True):
```

and
```
def testDate(year, month, day):
```
should be
```
def test_date(year, month, day):
```
Since the `includeCoordinationNumber` is not yet released on PyPi And the `testDate` function should not be used directly, I guess it's fine to change them without considering them as breaking changes.

P.S. It's probably even better to call the `testDate` function as `_test_date`.

[pep8-naming-conventions]: https://www.python.org/dev/peps/pep-0008/#naming-conventions

**Comment by frozzare** [comment]
Merged #10
